### ---------------------------------------------------------------- ###
### functions for data processing and analysis:
###  1. load text data file
###
### version 0.1, Sep 2015
### author: RS
### ---------------------------------------------------------------- ###

fImportData <- function(data.dir, data.fn, miss.flag, ...) {
  ## 1. load data from a text file (*.csv, *.dat), convert date/time
  ## to chron, replace missing data points with NA
  ##
  ## NB: time strings must have hours, minutes and seconds
  ##
  ## input:
  ##    data.dir = data file directory
  ##    data.fn = name of data file
  ##    miss.flag = missing value flag (e.g., -9999)
  ##    ... = date/time strings (e.g., "d/m/y h:m:s", "h:m:s")
  ## output:
  ##    data.out = data.frame ( time variables, data variables )
  ## ------------------------------------------------------------
  ## select type of data file
  fn.num <- nchar(data.fn)
  fn.ext <- substr(data.fn, (fn.num - 3), (fn.num))
  if (fn.ext == ".csv") {         # comma delimited
    fn.sep <- ","
  } else if (fn.ext == ".txt") {  # tab delimited
    fn.sep <- "\t"
  } else if (fn.ext == ".dat") {  # tab/space delimited
    fn.sep <- ""
  } else {
    stop("invalid file extension")
  }
  ## load data file
  data.file <- paste(data.dir, data.fn, sep="")
  data.df <- read.delim(data.file, header=TRUE, sep=fn.sep)
  ## convert date/time strings to chron
  time.fmt <- list(...)
  n.time <- length(time.fmt)
  time.df <- list()
  for (t in 1:n.time) {
    time.vec <- fChronStr(data.df[[t]], time.fmt[[t]])
    time.df[[t]] <- time.vec
  }
  time.df <- as.data.frame(time.df) #!
  colnames(time.df) <- colnames(data.df[1:n.time])
  ## set missing values to NA
  data.filt <- data.df[(n.time+1):ncol(data.df)]
  data.filt[data.filt == miss.flag] <- NA
  data.filt[is.na(data.filt)] <- NA
  ## output data.frame
  n.data <- ncol(data.df)
  data.out <- cbind(time.df, data.filt)
  return(data.out)
}

fLoadGGA <- function(gga.dir, gga.name, pl) {
  ## . load data file generated by the LosGatos instrument
  ##
  ## input:
  ##       gga.dir = data file directory
  ##       gga.name = name of data file
  ##       pl = "yes" or "no"
  ## output:
  ##        data.frame ( time variables, data variables )
  ##        --> plot (if pl = "yes")
  ## ------------------------------------------------------------
  ## load data file
  gga.file <- paste(gga.dir, gga.name, sep="")
  gga.text <- read.delim(gga.file, skip=1, header=TRUE, strip.white=TRUE,
                         sep=",")
  ## correct name of variables
  colnames(gga.text) <- gsub("X\\.", "", colnames(gga.text))
  colnames(gga.text) <- gsub("\\._", "_", colnames(gga.text))
  ## remove PGP signature
  gga.n <- which(gga.text$Time == "-----BEGIN PGP MESSAGE-----")
  gga.data <- gga.text[1:(gga.n-1),]
  ## convert timestamp to chron
  gga.time <- fChronStr(gga.data$Time, "d/m/y h:m:s")
  ## make plot (if requested)
  if (pl == "yes") {
  pl.file <- paste(strsplit(gga.name, "\\.")[[1]], ".png", sep="")
    png(pl.file, width=297, height=210, units="mm", res=150)
    par(mfrow=c(3,2))
    plot(gga.time, gga.data$CH4_ppm, type="l",
         main="CH4", xlab="Time", ylab="ppm")
    lines(gga.time, gga.data$CH4.d_ppm, col="blue")
    plot(gga.time, gga.data$CO2_ppm, type="l",
         main="CO2", xlab="Time", ylab="ppm")
    lines(gga.time, gga.data$CO2.d_ppm, col="blue")
    plot(gga.time, gga.data$H2O_ppm, type="l",
         main="H2O", xlab="Time", ylab="ppm")
    plot(gga.time, gga.data$GasP_torr, type="l",
         main="Gas Press", xlab="Time", ylab="torr")
    plot(gga.time, gga.data$GasT_C, type="l",
         main="Gas Temp", xlab="Time", ylab="C")
    plot(gga.time, gga.data$AmbT_C, type="l",
         main="Ambient Temp", xlab="Time", ylab="C")
    dev.off()
    }
  ## output data.frame
  gga.out <- cbind(gga.time, gga.data[,-1])
  colnames(gga.out)[1] <- "Datetime_UTC"
  return(gga.out)
}


fImportNA <- function(data.dir, data.fn) {
  data.file <- paste(data.dir, data.fn, sep="")
  data.df <- read.delim(data.file, header=TRUE, sep=fn.sep)
}
